"""role add description

Revision ID: 289f0b7caa30
Revises: 762012e3f481
Create Date: 2023-07-25 21:04:13.806272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289f0b7caa30'
down_revision = '762012e3f481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_roles', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_roles', 'description')
    # ### end Alembic commands ###
