"""initial_migration

Revision ID: 762012e3f481
Revises: 502099c99a4d
Create Date: 2023-07-22 13:25:10.167233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762012e3f481'
down_revision = '502099c99a4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
